### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by qzhang-ucr** [soarlab/FPTuner#4]
Hi,
I am trying to build and use FPTuner in an Ubuntu 16.04 x86_64 machine. I installed the latest Gurobi, but the FPTuner build fails in InstallFPTaylor. What should I do to fix this? 

Downloading FPTaylor git repository at branch develop
Checking out FPTaylor at commit bb773cb0e9e1b13db8845623e80186e1a343bb11
Building FPTaylor
File "fpu.ml", line 24, characters 0-52:
Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
File "fpu.ml", line 25, characters 0-54:
Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
File "fpu.ml", line 26, characters 0-60:
Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
File "fpu.ml", line 24, characters 0-52:
Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
File "fpu.ml", line 25, characters 0-54:
Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
File "fpu.ml", line 26, characters 0-60:
Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
/usr/bin/ld: chcw.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
File "_none_", line 1:
Error: Error while building custom runtime system
Makefile:23: recipe for target 'ocamlfpu' failed
make[1]: *** [ocamlfpu] Error 2
Makefile:71: recipe for target 'compile-interval' failed
make: *** [compile-interval] Error 2
Traceback (most recent call last):
  File "setup.py", line 258, in <module>
    main(sys.argv)
  File "setup.py", line 199, in main
    InstallFPTaylor("develop", "bb773cb0e9e1b13db8845623e80186e1a343bb11")
  File "setup.py", line 83, in InstallFPTaylor
    assert(os.path.isfile("./fptaylor"))
AssertionError

Thank you very much.

**Comment by huanghx1990** [comment]
Hi I also have this fail, did you fix it? could you share your approach Thanks very much

**Comment by huanghx1990** [comment]
> Hi,
> I am trying to build and use FPTuner in an Ubuntu 16.04 x86_64 machine. I installed the latest Gurobi, but the FPTuner build fails in InstallFPTaylor. What should I do to fix this?
> 
> Downloading FPTaylor git repository at branch develop
> Checking out FPTaylor at commit bb773cb0e9e1b13db8845623e80186e1a343bb11
> Building FPTaylor
> File "fpu.ml", line 24, characters 0-52:
> Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
> File "fpu.ml", line 25, characters 0-54:
> Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
> File "fpu.ml", line 26, characters 0-60:
> Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
> File "fpu.ml", line 24, characters 0-52:
> Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
> File "fpu.ml", line 25, characters 0-54:
> Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
> File "fpu.ml", line 26, characters 0-60:
> Warning 3: deprecated: [@@noalloc] should be used instead of "noalloc"
> /usr/bin/ld: chcw.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
> /usr/bin/ld: final link failed: Nonrepresentable section on output
> collect2: error: ld returned 1 exit status
> File "_none_", line 1:
> Error: Error while building custom runtime system
> Makefile:23: recipe for target 'ocamlfpu' failed
> make[1]: *** [ocamlfpu] Error 2
> Makefile:71: recipe for target 'compile-interval' failed
> make: *** [compile-interval] Error 2
> Traceback (most recent call last):
> File "setup.py", line 258, in
> main(sys.argv)
> File "setup.py", line 199, in main
> InstallFPTaylor("develop", "bb773cb0e9e1b13db8845623e80186e1a343bb11")
> File "setup.py", line 83, in InstallFPTaylor
> assert(os.path.isfile("./fptaylor"))
> AssertionError
> 
> Thank you very much.

I also have this error, did you fix it？if you do, could you share your solution?

**Comment by zvonimir** [comment]
Thanks for reporting this! Unfortunately, students who implemented FPTuner graduated a few years ago, and currently there is nobody maintaining FPTuner. So I am not sure how we would be able to help. Sorry!

**Comment by IanBriggs** [comment]
The issue relates to the version of FPTaylor being used. This used to be solvable by lowering the version of ocamlc in opam.

Modern versions of ocamlc provided by opam can no longer compile the version of FPTaylor used. Updating the FPTaylor version would require rewriting the interface between FPTuner and FPTaylor.

**Comment by huanghx1990** [comment]
> The issue relates to the version of FPTaylor being used. This used to be solvable by lowering the version of ocamlc in opam.
> 
> Modern versions of ocamlc provided by opam can no longer compile the version of FPTaylor used. Updating the FPTaylor version would require rewriting the interface between FPTuner and FPTaylor.

Hi, Ian, could you give the detail version of ocamlc for the fptuner installation? Thanks very much
